### ISSUE TITLE
Pre QC of reads

### ISSUE THREAD

**Issue by alethomas** [IKIM-Essen/uncovar#112]
- [x] check if incoming samples are empty and exclude them from transfer

**Comment by alethomas** [comment]
check for decent number of reads in raw files

**Comment by thomasbtf** [comment]
Had this problem again with sample 104195 from 2021-05-17:

104195 28 initial reads 
104195 6 reads after clipping

**Comment by thomasbtf** [comment]
I'll close this due to inactivtiy
