### ISSUE TITLE
Comparison with top sequence hit at variant resolution

### ISSUE THREAD

**Issue by johanneskoester** [IKIM-Essen/uncovar#3]
Once you have added the sourmash based selection of the closest accession/sequence, I plan to do the following:

1. map the sequence against the Wuhan reference with the minimap2 assembly-mapping mode.
2. Infer a VCF from the minimap2 output via paftools.
3. Create one of the variant reports I've shown you with the sample variants AND the variants of the closest sequence, thereby visualizing individual differences in the matrix.

**Comment by thomasbtf** [comment]
This is somehow related #392. I'll like #392 to this issue, as it has been stale for some time and #392 is going in the same direction.
