### ISSUE TITLE
Problem: workflow stops if one sample doesn't meet fast_pe requirements

### ISSUE THREAD

**Issue by AKBrueggemann** [IKIM-Essen/uncovar#303]
If the quality of one sample does not meet the required phred score, the fast_pe is empty and the workflow stops. This should be fixed, so that the workflow is still working, even if one sample can't be taken into account.

**Comment by AKBrueggemann** [comment]
The problem does not lie in the fatsp_pe rule, but in the clip_primer rule in read_clipping.smk. The output fastq.gz files are empty and the rule assembly_spades is missing its inputs. This error only appeared once for specific samples, that all lacked the required number of reads.

**Comment by thomasbtf** [comment]
@AKBrueggemann Is this still open or can we close this? :)

**Comment by thomasbtf** [comment]
AK: This is still open in principle, but I'm not sure if it's something that can be fixed at all. So far, this has only happened once with samples that had bad quality across the board.

**Comment by thomasbtf** [comment]
I`ll close this for now. If it happens again, please reopen this.
