### ISSUE TITLE
 Using the Snakemake Workflow Catalogue as deployment results in SyntaxError

### ISSUE THREAD

**Issue by thomasbtf** [IKIM-Essen/uncovar#336]
When using the Snakemake Workflow Catalogue (thus `snakedeploy`)  for "installing" UnCoVar, the following error occurs:
```python
SyntaxError in line 14 of /Users/btf/Projects/uncovar-snakedeploy/workflow/Snakefile:
invalid syntax (Snakefile, line 14)
```

This can be solved by removing the quotes in the Sankefile, line 13 and change 
```python
"github("IKIM-Essen/uncovar", path="workflow/Snakefile", tag="v0.3.0")"
```
to
```python
github("IKIM-Essen/uncovar", path="workflow/Snakefile", tag="v0.3.0")
```

This problem is already known (see https://github.com/snakemake/snakedeploy/issues/22) and will be fixed soon (see https://github.com/snakemake/snakedeploy/pull/23) 😊

**Comment by thomasbtf** [comment]
@lenakinzel, the above-mentioned PR is now merged. Could you please try the workflow catalogue deployment method again?

If it works please close this issue. Thanks 🙂

**Comment by lenakinzel** [comment]
The SyntaxError for running the workflow with the catalogue deployment method is no longer present. The mentioned PR merge fixed the issue.
