### ISSUE TITLE
Standardise nomenclature of variants of concern and Variants of interest

### ISSUE THREAD

**Issue by thomasbtf** [IKIM-Essen/uncovar#344]
In the config.yaml, the "variants to be highlighted" are called `variants of concern` (https://github.com/IKIM-Essen/uncovar/blob/master/config/config.yaml#L89).

In the report, the "variants to be highlighted" are called" `Variants of interest`(https://github.com/IKIM-Essen/uncovar/blob/master/workflow/scripts/generate-overview-table.py#L206).

This non-uniform nomenclature is confusing and wrong to use for single Mutations.

We should rename it in something like `Mutation Profiles of VOC/VOIs`. Maybe we should even split the `Variants of interest` into `Variants of Concern`, `Variants of Interest`, `Variants Under Monitoring` and find an automated way to get the latest Variants of something. Maybe pangolin repo offers VOCs, VOIs, and VUMs.

Who definitions are: (https://www.who.int/en/activities/tracking-SARS-CoV-2-variants/)

**Variants of Concern (VOC)**
A SARS-CoV-2 variant that meets the definition of a VOI (see below) and, through a comparative assessment, has been demonstrated to be associated with one or more of the following changes at a degree of global public health significance: 

- Increase in transmissibility or detrimental change in COVID-19 epidemiology; OR
- Increase in virulence or change in clinical disease presentation; OR
- Decrease in effectiveness of public health and social measures or available diagnostics, vaccines, therapeutics. 

**Variants of Interest (VOI)**
A SARS-CoV-2 variant : 

- with genetic changes that are predicted or known to affect virus characteristics such as transmissibility, disease severity, immune escape, diagnostic or therapeutic escape; AND 
- Identified to cause significant community transmission or multiple COVID-19 clusters, in multiple countries with increasing relative prevalence alongside increasing number of cases over time, or other apparent epidemiological impacts to suggest an emerging risk to global public health.  

**Variants Under Monitoring (VUM)**
A SARS-CoV-2 variant with genetic changes that are suspected to affect virus characteristics with some indication that it may pose a future risk, but evidence of phenotypic or epidemiological impact is currently unclear, requiring enhanced monitoring and repeat assessment pending new evidence.

**Comment by AKBrueggemann** [comment]
Closed with Pr #416
