### ISSUE TITLE
Question: anonynmous file

### ISSUE THREAD

**Issue by alethomas** [IKIM-Essen/uncovar#456]
https://github.com/IKIM-Essen/uncovar/blob/e844fc40923fcaa8c680079a05cd09173027fb00/workflow/rules/long_read.smk#L55

can this anonynmous addressing of the file cause problems, when were removing it with the next rule?

**Comment by alethomas** [comment]
https://github.com/IKIM-Essen/uncovar/blob/e844fc40923fcaa8c680079a05cd09173027fb00/workflow/rules/long_read.smk#L85

**Comment by thomasbtf** [comment]
Go catch 👍

**Comment by thomasbtf** [comment]
But just for completeness, what kind of problem did this produce?
