### ISSUE TITLE
Primer clipping

### ISSUE THREAD

**Issue by thomasbtf** [IKIM-Essen/uncovar#502]
## Version

- UnCoVar version: v0.13.2
- OS: Linux
- Snakemake version: 6.10.0

## Bug Report

The primer clipping doesn't seem to work. Can see from 3. Sequencing Details -> 4. Correct Amplicon Primer Clipping.

## Minimal Example

See run from 2022-03-18.

## Additional context

![2bdec83c22862194c5fcf4bb9197f82719600aea065e2c899f789017fdfb3c4a (1)](https://user-images.githubusercontent.com/46334240/159115157-37c76e62-7380-430e-a4a2-6fd3a9df478d.png)

**Comment by alethomas** [comment]
<img width="1086" alt="Bildschirmfoto 2022-03-22 um 10 43 16" src="https://user-images.githubusercontent.com/77535027/159452217-8f1189b2-b908-460c-b54a-45c022075180.png">

When using the correct primer file, the primer clipping works properly
